restructure for advanced tests

diff --git a/.github/workflows/texrefchk.yml b/.github/workflows/texrefchk.yml
--- a/.github/workflows/texrefchk.yml
+++ b/.github/workflows/texrefchk.yml
@@ -33,13 +33,13 @@ jobs:
       - name: OS Version
         run: |
           cat /etc/os-release
-      - name: texrefchk (Pass)
+      - name: texrefchk_pass_general
         run: |
-          /bin/bash -c ' ret=$(./texrefchk.sh --texdir=./test/01_pass); \
-                         if [ 0 -eq $? ]; then echo "[ PASS ]   test: 01_pass"; else [ FAIL ]   test: 01_pass; echo "$ret"; exit 1; fi; \
+          /bin/bash -c ' ret=$(./texrefchk.sh --texdir=./test/01_pass_general); \
+                         if [ 0 -eq $? ]; then echo "[ PASS ]   test: 01_pass_general"; else [ FAIL ]   test: 01_pass_general; echo "$ret"; exit 1; fi; \
                        '
-      - name: texrefchk (Fail)
+      - name: texrefchk_fail_general
         run: |
-          /bin/bash -c ' ret=$(./texrefchk.sh --texdir=./test/02_fail); \
-                         if [ 1 -eq $? ]; then echo "[ PASS ]   test: 02_fail"; else [ FAIL ]   test: 02_fail; echo "$ret"; exit 1; fi; \
+          /bin/bash -c ' ret=$(./texrefchk.sh --texdir=./test/10_fail_general); \
+                         if [ 1 -eq $? ]; then echo "[ PASS ]   test: 10_fail_general"; else [ FAIL ]   test: 10_fail_general; echo "$ret"; exit 1; fi; \
                        '
