run in subshell to pass exit 1 by

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -39,7 +39,6 @@ jobs:
           if [ 0 -eq $? ]; then echo "[ PASS ]   test: 01_pass"; else [ FAIL ]   test: 01_pass; echo $ret; exit 1; fi;
       - name: texrefchk (Fail)
         run: |
-          ret=$(./texrefchk.sh --texdir=./test/02_fail)
-          exit 0
-          #if [ 1 -eq $? ]; then echo "[ PASS ]   test: 02_fail"; else [ FAIL ]   test: 02_fail; echo $ret; exit 1; fi;
-          #exit 1
+          /bin/bash -c ' ret=$(./texrefchk.sh --texdir=./test/02_fail) \
+                         if [ 1 -eq $? ]; then echo "[ PASS ]   test: 02_fail"; else [ FAIL ]   test: 02_fail; echo $ret; exit 1; fi; \
+                       '
